docviewer_downloader/docviewer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('docviewercore.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

docviewer_downloader/docviewercore/urls.py
from django.urls import path
from . import views


app_name = 'docviewercore'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('home/', views.home_view, name='home'),
    path("logout/", views.logout_request, name="logout"),
    path('filesuploaded/', views.filesuploaded_view, name="filesuploaded"),
    path('viewfile/', views.file_viewer, name="fileviewer"),
    path('download/', views.download, name="download"),
]

docviewer_downloader/docviewercore/forms.py
from django import forms

docviewer_downloader/docviewercore/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, FileResponse, Http404
import os

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('docviewercore:login')
    else:
        form = UserCreationForm()
    return render(request, 'docviewercore/signup.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('docviewercore:home')
    else:
        form = AuthenticationForm()
    return render(request, 'docviewercore/login.html', {'form':form})


def logout_request(request):
    logout(request)
    return redirect("docviewercore:home")


def home_view(request):
    if request.method == 'POST':
        for count, x in enumerate(request.FILES.getlist("files")):
            def handle_uploaded_file(f):
                with open('media/'+ str(x), 'wb+') as destination:
                    for chunk in f.chunks():
                        destination.write(chunk)
            handle_uploaded_file(x)
        return HttpResponseRedirect("/filesuploaded/")
    messages.success(request, os.listdir('media'))
    return render(request, 'docviewercore/home.html')

def filesuploaded_view(request):
    messages.success(request, 'Upload Successful')
    return HttpResponseRedirect("/home/")


def file_viewer(request):
    if request.method == 'POST':
        filename = request.POST.get('filename')
        extn = os.path.splitext(filename)[1][1:]
        if extn in ['jpg','JPG','jpeg','JPEG','png','PNG']:
            try:
                return FileResponse(open('media/'+ filename, 'rb'))
            except FileNotFoundError:
                raise Http404('not found')
        if extn == 'pdf' or extn == 'PDF':
            try:
                return FileResponse(open('media/'+ filename, 'rb'), content_type='application/pdf')
            except FileNotFoundError:
                raise Http404('not found')
        if extn == 'docx' or extn == 'DOCX':
            try:
                return FileResponse(open('media/'+ filename, 'rb'))
            except FileNotFoundError:
                raise Http404('not found')
        if extn == 'pptx' or extn == 'PPTX':
            try:
                return FileResponse(open('media/'+ filename, 'rb'))
            except FileNotFoundError:
                raise Http404('not found')
        
def download(request):
    if request.method == 'GET':
        filename = request.GET.get('filename')
        response = HttpResponse(content_type='application/force-download') 
        response['Content-Disposition'] = f'attachment; filename={filename}'
        response['X-Sendfile'] = f'media/{filename}'
        return response

docviewer_downloader/docviewercore/templates/docviewercore/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

docviewer_downloader/docviewercore/templates/docviewercore/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Welcome</title>
    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
</head>
<body>
    {% extends "./base.html" %}
    {% block content %}
    {%if user.username %}
    <h3><a href="{% url 'docviewercore:logout'%}">Logout</a></h3>
    <h1>Welcome, {{user.username}}</h1>
    <br><br>
    <h4>Please select one on more files to upload</h4>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="files" multiple />
        <button type="submit">Upload</button>
    </form>
    {% if messages %}
    {% for message in messages %}
    <p style="font-weight: bold;letter-spacing: 2px;">{{ message }}</p>
    {% endfor %}
    {% endif %}
    <hr>
    <h4>File Viewer</h4>
    <p>To view file contents please enter below the filename with extension from the above list</p>
    <form action="/viewfile/" method="post">
        {% csrf_token %}
        <input type="text" id="filename" name="filename" required>
        <input type="submit" value="ViewFile">
        <button id="download" onclick="window.location.href = '/download/'" type="button">Download File</button>
    </form>

    <script type="text/javascript">
        $('#download').click(function () {
            var filename = $("#filename").val()
            $.ajax(
                {
                    type: "GET",
                    url: "/download/",
                    data: {
                        filename: filename
                    },
                    success: function (data) {
                        console.log(data)
                    }
                })
        });
    </script>
    {% else %}
    <h3><a href="{% url 'docviewercore:login'%}">Login</a></h3>
    OR
    <h3><a href="{% url 'docviewercore:signup'%}">SignUp</a></h3>
    {% endif %}
    {% endblock content %}
</body>
</html>

docviewer_downloader/docviewercore/templates/docviewercore/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    {% extends "./base.html" %}
    {% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="LogIn">
    </form>
    <br>
    OR
    <h3><a href="{% url 'docviewercore:signup'%}">SignUp</a></h3>
    {% endblock content %}
</body>

</html>

docviewer_downloader/docviewercore/templates/docviewercore/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>

<body>
    {% extends "./base.html" %}
    {% block content %}
    <h1>Signup</h1>
    <form method="post">
        {% csrf_token %}
        {{  form.as_p }}
        <input type="submit" value="Signup">
    </form>
    <br>
    <h4>or Login <a href="{% url 'docviewercore:login' %}">here</a></h2>
        {% endblock content %}
</body>

</html>